version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python3 app.py'
    links:
      - db
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - db


  db:
    image: mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_DATABASE: gixxer
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    ports:
      - 3306:3306
    expose:
      - '3306'
